### labelEncoding

* sklearn.preprocessing.LabelEncoder
*Encode target labels with value between 0 and n_classes-1.

This transformer should be used to encode target values, i.e. y, and not the input X.

Read more in the User Guide.

New in version 0.12.

In [2]:
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelENCODER를 객체로 생성한 후, fit() 과 transform() 으로 label 인코딩 수행.
encoder = Label = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)


인코딩 변환값: [0 1 4 5 3 3 2 2]


In [3]:
print('인코딩 클래스:', encoder. classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [4]:
print('디코딩 원본 값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [ ]:
Titanic 데이터 전처리
suvived, Sex, Age, Embarked 컬럼만 이용하려고 한다.
피처는 sex = 남, age= 평균, Embarked =S 사용하고
레이블은 survived 사용하여 지도학습을 하려고 한다.
데이터의 전처리가 필요한 상황이라
데이터 전처리를 해야 하는데 결측치가 관찰이 되어서 결측치 처리를 해야 하고 문자열이 보여서 인코딩을 해줘야 한다.
결측치는 평균값으로 인코딩은 labelEncoding을 이용하여 처리한 결과를 데이터 프레임으로 출력


In [ ]:
•판다스를 이용해서 csv 읽어 오기
•필요한 칼러만 남기고 drop
•fillna를 활용하여 결측치 처리(mean)
•LabelEncoder를 활용하여 인코딩

### titanic.csv 전처리

In [46]:
import pandas as pd

df = pd.read_csv('C:/apps/ml/datasets/titanic.csv')

In [21]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [54]:
df.drop(columns = ['PassengerId', 'Pclass', 'Name', 'SibSp', 'Parch', 'Fare', 'Cabin'], inplace=True)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Survived  891 non-null    int64 
 1   Sex       891 non-null    object
 2   Age       891 non-null    int64 
 3   Ticket    891 non-null    object
 4   Embarked  891 non-null    object
dtypes: int64(2), object(3)
memory usage: 34.9+ KB


In [56]:
df['Age'].isnull().sum()

0

In [57]:
df['Age'] = df['Age'].fillna(df['Age'].mean())


In [58]:
df['Age'].isnull().sum()

0

In [59]:
df['Embarked'] = df['Embarked'].fillna('S')

In [48]:
df['Embarked'].isnull().sum()

0

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Survived  891 non-null    int64 
 1   Sex       891 non-null    object
 2   Age       891 non-null    int64 
 3   Ticket    891 non-null    object
 4   Embarked  891 non-null    object
dtypes: int64(2), object(3)
memory usage: 34.9+ KB


In [52]:
# Sex , Embarked encoding 
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['Age'] = encoder.fit_transform(df['Age'])

In [53]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex  Age  SibSp  \
0                              Braund, Mr. Owen Harris    male   28      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   51      1   
2                               Heikkinen, Miss. Laina  female   34      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   47      1   
4                             Allen, Mr. William Henry    male   47      0   
..                                                 ...     ...  ...    ...   
886                              Montvila, Rev. Juozas    male   35      0   
887                       Graham, Miss. Margaret Edith  female   24      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   88      1   
889                              Behr, Mr. Karl Howell    male   34      0   
890                                Dooley, Mr. Patrick    male   42      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

### OneHotEncoder
OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None)

In [64]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', ' 믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환합니다.
labels = labels.reshape(-1,1)

# 원-핫 인코딩을 적용합니다.
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 7)


In [65]:
import numpy as np
items = ['TV', '냉장고', ]

one_encoder = OneHotEncoder ()
# items = items.reshape(-1,1)
# np.array(items).reshape(-1,1)
items = np.array(items).reshape(-1,1)
data = one_encoder.fit_transform(items)

## cross_val_score
- estimator: estimator <br>
    학습을 할 모델
- x: array <br>
    학습시킬 훈련 데이터 세트
- y: array<br>
   학습시킬 훈련 데이터 세트의 Label
- scoring: string or None<br>
    각 모델에서 사용할 평가 방법
    교차 검증은 utility function을 사용. 그래서 더 큰 값이 좋은 결과라는 의미입니다.<br>
    위와 같은 이유로 Regression 모델에서는 MSE를 얻기 위해 주로 'neg_mean_squred_error'값을 사용합니다. (0으로 갈수록 좋은 점수).<br>
- cv: int or kfold<br>
   : Cross-Validation generator.<br>
    Fold의 수를 의미<br>
- scores: returns, array
    scoring을 사용하여 평가한 점수를 각각 교차 검증을 반복 시마다 기록하여 돌려줌
## cross_validate()
> 다중 평가 지표는 모델을 평가할 때 여러 개의 지표를 사용하여 모델을 평가한다는 의미
- cross_val_score와 파라미터는 유사
- cross_val_score()와 마찬가지로 scoring 매개변수를 통하여 평가 지표를 지정. 다중 평가 지표를 사용하고자 한다면 리스트로 작성하여 전달, 즉  scoring 매개변수에서 리스트로 여러 평가 지표를 전달
- return_train_score: cross_val_score와 다르게 테스트 폴드 점수뿐 아니라 훈련 폴드에 대한 점수를 리턴 할 수 있음. 훈련 폴드의 점수를 받을지 여부를 설정하는 변수

### pandas.get_dummies
pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)

참고사항 : https://pandas.pydata.org/docs/reference/api/pandas.get_dummies.html

### pandas.get_dummies

In [69]:
import pandas as pd


In [72]:
df = pd.read_csv('./datasets/titanic.csv')
df.drop(columns = ['PassengerId','Pclass','Name','SibSp', 'Parch','Ticket','Fare','Cabin'],inplace=True)
df

Survived     Sex   Age Embarked
0           0    male  22.0        S
1           1  female  38.0        C
2           1  female  26.0        S
3           1  female  35.0        S
4           0    male  35.0        S
..        ...     ...   ...      ...
886         0    male  27.0        S
887         1  female  19.0        S
888         0  female   NaN        S
889         1    male  26.0        C
890         0    male  32.0        Q

[891 rows x 4 columns]

In [74]:
df['Age']  = df['Age'].fillna(df['Age'].mean() )
df['Embarked'] = df['Embarked'].fillna('S')
df

Survived     Sex        Age Embarked
0           0    male  22.000000        S
1           1  female  38.000000        C
2           1  female  26.000000        S
3           1  female  35.000000        S
4           0    male  35.000000        S
..        ...     ...        ...      ...
886         0    male  27.000000        S
887         1  female  19.000000        S
888         0  female  29.699118        S
889         1    male  26.000000        C
890         0    male  32.000000        Q

[891 rows x 4 columns]

In [75]:
data = df.loc[:,'Embarked']
data

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [76]:
dummy_embark = pd.get_dummies(data)

In [82]:
dummy_data = pd.get_dummies(df[['Sex', 'Embarked']])
dummy_data

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           0           1
1             1         0           1           0           0
2             1         0           0           0           1
3             1         0           0           0           1
4             0         1           0           0           1
..          ...       ...         ...         ...         ...
886           0         1           0           0           1
887           1         0           0           0           1
888           1         0           0           0           1
889           0         1           1           0           0
890           0         1           0           1           0

[891 rows x 5 columns]

In [84]:
df3 = pd.concat([df, dummy_data], axis=1)
df3

Survived     Sex        Age Embarked  Sex_female  Sex_male  Embarked_C  \
0           0    male  22.000000        S           0         1           0   
1           1  female  38.000000        C           1         0           1   
2           1  female  26.000000        S           1         0           0   
3           1  female  35.000000        S           1         0           0   
4           0    male  35.000000        S           0         1           0   
..        ...     ...        ...      ...         ...       ...         ...   
886         0    male  27.000000        S           0         1           0   
887         1  female  19.000000        S           1         0           0   
888         0  female  29.699118        S           1         0           0   
889         1    male  26.000000        C           0         1           1   
890         0    male  32.000000        Q           0         1           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 9 columns]

In [85]:
df3.drop(columns=['Sex','Embarked'] , inplace = True)
df3

Survived        Age  Sex_female  Sex_male  Embarked_C  Embarked_Q  \
0           0  22.000000           0         1           0           0   
1           1  38.000000           1         0           1           0   
2           1  26.000000           1         0           0           0   
3           1  35.000000           1         0           0           0   
4           0  35.000000           0         1           0           0   
..        ...        ...         ...       ...         ...         ...   
886         0  27.000000           0         1           0           0   
887         1  19.000000           1         0           0           0   
888         0  29.699118           1         0           0           0   
889         1  26.000000           0         1           1           0   
890         0  32.000000           0         1           0           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 7 columns]